### ISSUE TITLE
Link in README.md does not work

### ISSUE THREAD

**Issue by mafla** [TrevorJA/Ipywidget_Demo_Interactive_HYMOD#1]
Great work, but the "The tutorial can be viewed through a [Jupyter Notebook Binder at this link](https://hub-binder.mybinder.ovh/user/trevorja-ipywid-teractive_hymod-vy1rlyq8/doc/tree/Interactive%20HYMOD%20Ipywidget.ipynb)" is broken.

**Comment by TrevorJA** [comment]
Thank you for pointing this out!  
The link is fixed.
